const mails = [
  {
    id: 0,
    sender: 'John Doe',
    subject: 'Hello World',
    body: 'Lorem ipsum dolor sit amet, consectetur adipiscing Lorem ipsum dolor sit amet, consectetur adipiscingLorem ipsum dolor sit amet, consectetur adipiscing',
    date: "Jan 24",
    read: true,
    starred: true,
  },
  {
    id: 1,
    sender: 'Jane Smith',
    subject: 'Meeting Reminder',
    body: 'Hi there, Just a quick reminder that our meeting is scheduled for tomorrow at 10am. Please make sure to attend on time. Thanks!',
    date: "Feb 12",
    read: false,
    starred: false,
  },
  {
    id: 2,
    sender: 'Mark Johnson',
    subject: 'Important Announcement',
    body: 'Dear all, I am writing to inform you that our company has been acquired by a larger organization. There will be some changes to the way we work, but we will try to make the transition as smooth as possible. Please feel free to contact me if you have any questions or concerns. Best, Mark',
    date: "Mar 1",
    read: true,
    starred: true,
  },
  {
    id: 3,
    sender: 'Sarah Lee',
    subject: 'Happy Birthday!',
    body: 'Dear friend, Just wanted to wish you a very happy birthday! I hope you have a great day filled with joy and celebration. Best wishes, Sarah',
    date: "Mar 5",
    read: false,
    starred: false,
  },
  {
    id: 4,
    sender: 'Alex Chen',
    subject: 'New Product Launch',
    body: 'Hello everyone, We are excited to announce the launch of our new product line. Please visit our website to learn more and place your orders. Thank you for your continued support. Best regards, Alex',
    date: "Mar 7",
    read: false,
    starred: false,
  },
  {
    id: 5,
    sender: 'Karen Wong',
    subject: 'Vacation Request',
    body: 'Hi manager, I would like to request vacation time from March 15 to March 22. Please let me know if this is possible. Thank you, Karen',
    date: "Mar 9",
    read: false,
    starred: false,
  },
  {
    id: 6,
    sender: 'Jack Liu',
    subject: 'Meeting Minutes',
    body: 'Hello team, Please find attached the minutes from our meeting yesterday. Let me know if you have any questions or concerns. Best, Jack',
    date: "Mar 9",
    read: true,
    starred: false,
  },
  {
    id: 7,
    sender: 'Megan Brown',
    subject: 'Project Update',
    body: 'Dear colleagues, I wanted to give you a quick update on our project progress. We have completed 50% of the work and are on track to meet our deadline. Thanks for your hard work and dedication. Best, Megan',
    date: "Mar 8",
    read: true,
    starred: false,
  },
  {
    id: 8,
    sender: 'Chris Evans',
    subject: 'Job Opportunity',
    body: 'Hi there, I came across your profile and wanted to reach out about a job opportunity at our company. We are looking for a talented developer to join our team. Please let me know if you are interested and we can schedule an interview. Best, Chris',
    date: "Mar 6",
    read: false,
    starred: false,
  },
  {
    id: 9,
    sender: 'John Doe',
    subject: 'Hello World',
    body: 'Lorem ipsum dolor sit amet, consectetur adipiscing Lorem ipsum dolor sit amet, consectetur adipiscingLorem ipsum dolor sit amet, consectetur adipiscing',
    date: "Jan 24",
    read: false,
    starred: false,
  },
  {
    id: 10,
    sender: 'Jane Smith',
    subject: 'Meeting Reminder',
    body: 'Hi there, Just a quick reminder that our meeting is scheduled for tomorrow at 10am. Please make sure to attend on time. Thanks!',
    date: "Feb 12",
    read: false,
    starred: false,
  },
  {
    id: 11,
    sender: 'Mark Johnson',
    subject: 'Important Announcement',
    body: 'Dear all, I am writing to inform you that our company has been acquired by a larger organization. There will be some changes to the way we work, but we will try to make the transition as smooth as possible. Please feel free to contact me if you have any questions or concerns. Best, Mark',
    date: "Mar 1",
    read: true,
    starred: false,
  },
  {
    id: 12,
    sender: 'Sarah Lee',
    subject: 'Happy Birthday!',
    body: 'Dear friend, Just wanted to wish you a very happy birthday! I hope you have a great day filled with joy and celebration. Best wishes, Sarah',
    date: "Mar 5",
    read: false,
    starred: false,
  },
  {
    id: 13,
    sender: 'Alex Chen',
    subject: 'New Product Launch',
    body: 'Hello everyone, We are excited to announce the launch of our new product line. Please visit our website to learn more and place your orders. Thank you for your continued support. Best regards, Alex',
    date: "Mar 7",
    read: false,
    starred: false,
  },
  {
    id: 14,
    sender: 'Karen Wong',
    subject: 'Vacation Request',
    body: 'Hi manager, I would like to request vacation time from March 15 to March 22. Please let me know if this is possible. Thank you, Karen',
    date: "Mar 9",
    read: false,
    starred: false,
  },
  {
    id: 15,
    sender: 'Jack Liu',
    subject: 'Meeting Minutes',
    body: 'Hello team, Please find attached the minutes from our meeting yesterday. Let me know if you have any questions or concerns. Best, Jack',
    date: "Mar 9",
    read: true,
    starred: false,
  },
  {
    id: 16,
    sender: 'Megan Brown',
    subject: 'Project Update',
    body: 'Dear colleagues, I wanted to give you a quick update on our project progress. We have completed 50% of the work and are on track to meet our deadline. Thanks for your hard work and dedication. Best, Megan',
    date: "Mar 8",
    read: true,
    starred: false,
  },
  {
    id: 17,
    sender: 'Chris Evans',
    subject: 'Job Opportunity',
    body: 'Hi there, I came across your profile and wanted to reach out about a job opportunity at our company. We are looking for a talented developer to join our team. Please let me know if you are interested and we can schedule an interview. Best, Chris',
    date: "Mar 6",
    read: false,
    starred: false,
  },
  {
    id: 18,
    sender: 'Alex Chen',
    subject: 'New Product Launch',
    body: 'Hello everyone, We are excited to announce the launch of our new product line. Please visit our website to learn more and place your orders. Thank you for your continued support. Best regards, Alex',
    date: "Mar 7",
    read: false,
    starred: false,
  },
  {
    id: 19,
    sender: 'Karen Wong',
    subject: 'Vacation Request',
    body: 'Hi manager, I would like to request vacation time from March 15 to March 22. Please let me know if this is possible. Thank you, Karen',
    date: "Mar 9",
    read: false,
    starred: false,
  },
  {
    id: 20,
    sender: 'Jack Liu',
    subject: 'Meeting Minutes',
    body: 'Hello team, Please find attached the minutes from our meeting yesterday. Let me know if you have any questions or concerns. Best, Jack',
    date: "Mar 9",
    read: true,
    starred: false,
  },
  {
    id: 21,
    sender: 'Megan Brown',
    subject: 'Project Update',
    body: 'Dear colleagues, I wanted to give you a quick update on our project progress. We have completed 50% of the work and are on track to meet our deadline. Thanks for your hard work and dedication. Best, Megan',
    date: "Mar 8",
    read: true,
    starred: false,
  },
  {
    id: 22,
    sender: 'Chris Evans',
    subject: 'Job Opportunity',
    body: 'Hi there, I came across your profile and wanted to reach out about a job opportunity at our company. We are looking for a talented developer to join our team. Please let me know if you are interested and we can schedule an interview. Best, Chris',
    date: "Mar 6",
    read: false,
    starred: false,
  },
]
export default mails;
